
  lane :android_test do
    puts("Testing Fastlane from Android")
  end

  lane :android_flutter do |options|
    build_number = options[:build_number]
    build_name = options[:build_name]
    skip_clean = options[:skip_clean]

    unless skip_clean
      sh("flutter", "clean")
      sh("flutter", "packages", "get")
    end

    Dir.chdir ".." do
      sh("shorebird", "release", "android",  "--flavor", "prod", "--force", "--", "--no-tree-shake-icons")
    end
    
  end

  lane :android_build_and_upload do |options|
    build_number = options[:build_number]
    build_name = options[:build_name]
    skip_clean = options[:skip_clean]
    type = options[:type]
    changelog = options[:changelog]
  
    if build_number || build_name
      android_flutter(build_number: build_number, build_name: build_name, skip_clean: skip_clean)
    end

    android_upload(
      type: options[:type],
      build_name: build_name,
      build_number: build_number,
      changelog: changelog,
    )
  end

  lane :android_upload do |options|
    build_number = options[:build_number].to_i
    build_name = options[:build_name]
    type = options[:type]
    changelog = options[:changelog]
    
    upload_to_play_store(
      track: "internal",
      aab: "./build/app/outputs/bundle/prodRelease/app-prod-release.aab",
      version_name: build_name,
      version_code: build_number,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true
    )

    if type == "beta"
      upload_to_play_store(
        track: "internal",
        track_promote_to: "beta",
        version_name: build_name,
        version_code: build_number,
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_screenshots: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true
      )
    elsif type == "release"
      upload_to_play_store(
        track: "internal",
        track_promote_to: "beta",
        version_name: build_name,
        version_code: build_number,
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_screenshots: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true
      )

      upload_to_play_store(
        track: "beta",
        track_promote_to: "production",
        version_name: build_name,
        version_code: build_number,
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_screenshots: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true
      )
    end
  end